//console.log('abc');

var DeviceID     = "%DeviceID%";
var InstallDate  = "%InstallDate%";
var UpTime       = "%UpTime%";
var FirmwareVer  = "%FirmwareVer%";
var CompileDate  = "%CompileDate%";
var ReleaseType  = "%ReleaseType%";
var NickName     = "%NickName%";
var LCDType      = "%LCDType%";
var SSID         = "%SSID%";
var SSH_SVR      = "%SSH_SVR%";
var SSH_UN       = "%SSH_UN%";
var SSH_PW       = "%SSH_PW%";
var SSH_Port     = "%SSH_Port%";
var MTConn       = "%MTConn%";
var GmailAddr    = "%GmailAddr%";
var GmailPW      = "%GmailPW%";
var ChatID       = "%ChatID%";
var BotID        = "%BotID%";
var AutoUpdate   = "%AutoUpdate%";
var AutoSetup    = "%AutoSetup%";
var StaticIP     = "%StaticIP%";
var SubNet       = "%SubNet%";
var RateMatrix   = "%RateMatrix%";
var PINS         = "%PINS%";
var CONFIG       = "%CONFIG%";
var RATES        = "%RATES%";
